//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP229_F16_Team_Project_1 {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new COMP229_F16_Team_Project_1.Site1 Master {
            get {
                return ((COMP229_F16_Team_Project_1.Site1)(base.Master));
            }
        }
    }
}
